# https://cloud.google.com/appengine/docs/standard/nodejs/config/appref
runtime: nodejs16
env: standard
instance_class: F1
service: frontend

default_expiration: "30m"

handlers:
- url: /favicon\.ico
  secure: always
  static_files: build/favicon.ico
  upload: build/favicon.ico

- url: /robots\.txt
  secure: always
  # 정적 파일 패턴 핸들러가 URL 패턴을 애플리케이션을 통해 업로드된 정적 파일의 경로와 연결합니다. 
  # URL 패턴 정규 표현식은 파일 경로 생성 시 사용할 정규 표현식 그룹을 정의할 수 있습니다. 
  # static_dir 대신 이 요소를 사용하면 전체 디렉터리를 매핑하지 않고도 디렉터리 구조의 특정 파일로 매핑할 수 있습니다.
  static_files: build/robots.txt
  upload: build/robots.txt

- url: /static
  secure: always
  # 애플리케이션 루트 디렉터리의 정적 파일을 포함하는 디렉터리의 경로입니다. 
  # 일치하는 url 패턴 끝 다음에 오는 모든 항목이 static_dir에 추가되어 요청된 파일에 대한 전체 경로를 구성합니다.
  static_dir: build/static

- url: /.*
  secure: always
  expiration: 10s
  static_files: build/index.html
  upload: build/index.html


automatic_scaling:
  min_idle_instances: 0
  max_idle_instances: 1
  max_concurrent_requests: 20
  min_pending_latency: automatic
  max_pending_latency: automatic
